### PR TITLE
README and license

### LINKED ISSUE #5: make LICENSE and README?
just to give people permissions and context, respectively.

### PR DESCRIPTION
**Pull request by Timed-kitty-cat**
Resolves #5

### CODE REVIEW

**Comment by gosoccerboy5** [comment]
lgtm

**Comment by gosoccerboy5** [comment]
merged! jk

**Comment by Timed-kitty-cat** [comment]
> lgtm

What?

**Comment by gosoccerboy5** [comment]
> > lgtm
> 
> What?

looks good to me/merge

**Comment by Timed-kitty-cat** [comment]
> > > lgtm
> > 
> > 
> > What?
> 
> looks good to me/merge

ok

**Comment by Timed-kitty-cat** [comment]
Time to do some commits.

**Comment by gosoccerboy5** [comment]
> > > > lgtm
> > > 
> > > 
> > > What?
> > 
> > 
> > looks good to me/merge
> 
> ok

who are you talking to? :p

**Comment by Timed-kitty-cat** [comment]
> > > > > lgtm
> > > > 
> > > > 
> > > > What?
> > > 
> > > 
> > > looks good to me/merge
> > 
> > 
> > ok
> 
> who are you talking to? :p

you :earth_americas:

**Comment by gosoccerboy5** [comment]
> > > > > > lgtm
> > > > > 
> > > > > 
> > > > > What?
> > > > 
> > > > 
> > > > looks good to me/merge
> > > 
> > > 
> > > ok
> > 
> > 
> > who are you talking to? :p
> 
> you 🌎

wut

**Comment by Timed-kitty-cat** [comment]
> > > > > > > lgtm
> > > > > > 
> > > > > > 
> > > > > > What?
> > > > > 
> > > > > 
> > > > > looks good to me/merge
> > > > 
> > > > 
> > > > ok
> > > 
> > > 
> > > who are you talking to? :p
> > 
> > 
> > you 🌎
> 
> wut

I was talking to you

**Comment by gosoccerboy5** [comment]
this pr needs some more discussion

**Comment by Timed-kitty-cat** [comment]
@FunctionalMetatable

**Pull request merged**
